// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddScheduledTask(arg1) {
  return window['go']['agent']['App']['AddScheduledTask'](arg1);
}

export function ClearHistory(arg1) {
  return window['go']['agent']['App']['ClearHistory'](arg1);
}

export function ConnectChannel(arg1) {
  return window['go']['agent']['App']['ConnectChannel'](arg1);
}

export function CreateBot(arg1) {
  return window['go']['agent']['App']['CreateBot'](arg1);
}

export function DeleteChannel(arg1) {
  return window['go']['agent']['App']['DeleteChannel'](arg1);
}

export function DeleteScheduledTask(arg1) {
  return window['go']['agent']['App']['DeleteScheduledTask'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['agent']['App']['DeleteSession'](arg1);
}

export function DisconnectChannel(arg1) {
  return window['go']['agent']['App']['DisconnectChannel'](arg1);
}

export function FetchProviderModels(arg1) {
  return window['go']['agent']['App']['FetchProviderModels'](arg1);
}

export function GetAllScheduledTasks() {
  return window['go']['agent']['App']['GetAllScheduledTasks']();
}

export function GetAuditRecords(arg1) {
  return window['go']['agent']['App']['GetAuditRecords'](arg1);
}

export function GetAuditStats(arg1) {
  return window['go']['agent']['App']['GetAuditStats'](arg1);
}

export function GetBotDetail(arg1) {
  return window['go']['agent']['App']['GetBotDetail'](arg1);
}

export function GetChannelStatus(arg1) {
  return window['go']['agent']['App']['GetChannelStatus'](arg1);
}

export function GetChannels() {
  return window['go']['agent']['App']['GetChannels']();
}

export function GetExecutionTrace(arg1, arg2) {
  return window['go']['agent']['App']['GetExecutionTrace'](arg1, arg2);
}

export function GetLatestTrace(arg1) {
  return window['go']['agent']['App']['GetLatestTrace'](arg1);
}

export function GetMemoryStatus() {
  return window['go']['agent']['App']['GetMemoryStatus']();
}

export function GetModelConfig() {
  return window['go']['agent']['App']['GetModelConfig']();
}

export function GetRequestLogs(arg1) {
  return window['go']['agent']['App']['GetRequestLogs'](arg1);
}

export function GetScheduledTasks(arg1) {
  return window['go']['agent']['App']['GetScheduledTasks'](arg1);
}

export function GetSessionHistory(arg1) {
  return window['go']['agent']['App']['GetSessionHistory'](arg1);
}

export function GetSessions() {
  return window['go']['agent']['App']['GetSessions']();
}

export function GetSkillDetail(arg1) {
  return window['go']['agent']['App']['GetSkillDetail'](arg1);
}

export function GetSkills() {
  return window['go']['agent']['App']['GetSkills']();
}

export function GetStorageAuditRecords(arg1) {
  return window['go']['agent']['App']['GetStorageAuditRecords'](arg1);
}

export function GetStorageAuditStats(arg1) {
  return window['go']['agent']['App']['GetStorageAuditStats'](arg1);
}

export function GetSystemInfo() {
  return window['go']['agent']['App']['GetSystemInfo']();
}

export function GetUsageStats() {
  return window['go']['agent']['App']['GetUsageStats']();
}

export function InstallClawHubSkill(arg1) {
  return window['go']['agent']['App']['InstallClawHubSkill'](arg1);
}

export function InstallMCPSkill(arg1) {
  return window['go']['agent']['App']['InstallMCPSkill'](arg1);
}

export function InstallSkill(arg1) {
  return window['go']['agent']['App']['InstallSkill'](arg1);
}

export function InstallSkillHubSkill(arg1) {
  return window['go']['agent']['App']['InstallSkillHubSkill'](arg1);
}

export function RefreshSkills() {
  return window['go']['agent']['App']['RefreshSkills']();
}

export function ReorderSessions(arg1) {
  return window['go']['agent']['App']['ReorderSessions'](arg1);
}

export function SaveChannel(arg1) {
  return window['go']['agent']['App']['SaveChannel'](arg1);
}

export function SaveModelProviders(arg1) {
  return window['go']['agent']['App']['SaveModelProviders'](arg1);
}

export function SearchClawHubSkills(arg1) {
  return window['go']['agent']['App']['SearchClawHubSkills'](arg1);
}

export function SearchSkillHubSkills(arg1) {
  return window['go']['agent']['App']['SearchSkillHubSkills'](arg1);
}

export function SendMessage(arg1, arg2, arg3) {
  return window['go']['agent']['App']['SendMessage'](arg1, arg2, arg3);
}

export function SetActiveModel(arg1, arg2) {
  return window['go']['agent']['App']['SetActiveModel'](arg1, arg2);
}

export function SetScheduledTaskEnabled(arg1, arg2) {
  return window['go']['agent']['App']['SetScheduledTaskEnabled'](arg1, arg2);
}

export function SetSkillEnabled(arg1, arg2) {
  return window['go']['agent']['App']['SetSkillEnabled'](arg1, arg2);
}

export function StartSystemMonitor() {
  return window['go']['agent']['App']['StartSystemMonitor']();
}

export function StopGenerate(arg1) {
  return window['go']['agent']['App']['StopGenerate'](arg1);
}

export function UninstallSkill(arg1) {
  return window['go']['agent']['App']['UninstallSkill'](arg1);
}

export function UpdateBot(arg1, arg2) {
  return window['go']['agent']['App']['UpdateBot'](arg1, arg2);
}

export function UpdateScheduledTask(arg1) {
  return window['go']['agent']['App']['UpdateScheduledTask'](arg1);
}
