// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {agent} from '../models';
import {audit} from '../models';
import {config} from '../models';
import {memory} from '../models';
import {skill} from '../models';

export function AddScheduledTask(arg1:agent.ScheduledTask):Promise<void>;

export function ClearHistory(arg1:string):Promise<void>;

export function ConnectChannel(arg1:string):Promise<void>;

export function CreateBot(arg1:agent.BotOptions):Promise<agent.Session>;

export function DeleteChannel(arg1:string):Promise<void>;

export function DeleteScheduledTask(arg1:string):Promise<void>;

export function DeleteSession(arg1:string):Promise<void>;

export function DisconnectChannel(arg1:string):Promise<void>;

export function FetchProviderModels(arg1:string):Promise<Array<string>>;

export function GetAllScheduledTasks():Promise<Array<agent.ScheduledTask>>;

export function GetAuditRecords(arg1:audit.SkillQuery):Promise<audit.SkillPageResult>;

export function GetAuditStats(arg1:number):Promise<audit.SkillStats>;

export function GetBotDetail(arg1:string):Promise<agent.Session>;

export function GetChannelStatus(arg1:string):Promise<boolean>;

export function GetChannels():Promise<Array<config.ChannelConfig>>;

export function GetExecutionTrace(arg1:string,arg2:string):Promise<agent.ExecutionTrace>;

export function GetLatestTrace(arg1:string):Promise<agent.ExecutionTrace>;

export function GetMemoryStatus():Promise<Record<string, any>>;

export function GetModelConfig():Promise<config.AppConfig>;

export function GetRequestLogs(arg1:string):Promise<Array<memory.LLMRequestLog>>;

export function GetScheduledTasks(arg1:string):Promise<Array<agent.ScheduledTask>>;

export function GetSessionHistory(arg1:string):Promise<Array<agent.Message>>;

export function GetSessions():Promise<Array<agent.Session>>;

export function GetSkillDetail(arg1:string):Promise<skill.Skill>;

export function GetSkills():Promise<Array<skill.Skill>>;

export function GetStorageAuditRecords(arg1:audit.StorageQuery):Promise<audit.StoragePageResult>;

export function GetStorageAuditStats(arg1:number):Promise<audit.StorageStats>;

export function GetSystemInfo():Promise<agent.SystemInfo>;

export function GetUsageStats():Promise<agent.UsageStats>;

export function InstallClawHubSkill(arg1:string):Promise<void>;

export function InstallMCPSkill(arg1:skill.Skill):Promise<void>;

export function InstallSkill(arg1:skill.Skill):Promise<void>;

export function InstallSkillHubSkill(arg1:string):Promise<void>;

export function RefreshSkills():Promise<Array<skill.Skill>>;

export function ReorderSessions(arg1:Array<string>):Promise<void>;

export function SaveChannel(arg1:config.ChannelConfig):Promise<void>;

export function SaveModelProviders(arg1:Array<config.ModelProvider>):Promise<void>;

export function SearchClawHubSkills(arg1:string):Promise<Array<skill.ClawHubSkill>>;

export function SearchSkillHubSkills(arg1:string):Promise<Array<skill.SkillHubSkill>>;

export function SendMessage(arg1:string,arg2:string,arg3:Array<agent.Attachment>):Promise<void>;

export function SetActiveModel(arg1:string,arg2:string):Promise<void>;

export function SetScheduledTaskEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SetSkillEnabled(arg1:string,arg2:boolean):Promise<void>;

export function StartSystemMonitor():Promise<void>;

export function StopGenerate(arg1:string):Promise<void>;

export function UninstallSkill(arg1:string):Promise<void>;

export function UpdateBot(arg1:string,arg2:agent.BotOptions):Promise<void>;

export function UpdateScheduledTask(arg1:agent.ScheduledTask):Promise<void>;
